[versions]
mavenPublish = "0.36.0"

[libraries]
javapoet = { group = "com.palantir.javapoet", name = "javapoet", version = "0.11.0" }

plugindep-mavenPublish = { group = "com.vanniktech.maven.publish", name = "com.vanniktech.maven.publish.gradle.plugin", version.ref = "mavenPublish" }

[plugins]
jmh = { id = "me.champeau.jmh", version = "0.7.3" }
